<a href="https://colab.research.google.com/github/James56555/Python-/blob/main/Treeclassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
s= pd.read_csv("/content/drive/MyDrive/Dataset/Movie_classification.csv", header=0)
df = pd.DataFrame(s)

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
df['Time_taken'].mean()

In [6]:
df['Time_taken'].fillna(value = df['Time_taken'].mean(), inplace = True)

In [ ]:
df.info()


In [8]:
df = pd.get_dummies(df,columns = ["3D_available","Genre"],drop_first = True)

In [ ]:
df.head()

In [10]:
df['3D_available_YES'] = df['3D_available_YES'].astype(int)
df['Genre_Comedy'] = df['Genre_Comedy'].astype(int)
df['Genre_Drama'] = df['Genre_Drama'].astype(int)
df["Genre_Thriller"] = df["Genre_Thriller"].astype(int)

In [ ]:
df.info()

In [ ]:
X = df.loc[:,df.columns!="Start_Tech_Oscar"]
type(X)

In [ ]:
X.head()

In [ ]:
X.shape

In [ ]:
y = df["Start_Tech_Oscar"]
type(y)

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42)

In [ ]:
X_train.head()


In [ ]:
X_train.shape

In [ ]:
X_test.shape


In [21]:
from sklearn import tree
clftree = tree.DecisionTreeClassifier(max_depth = 3)

In [22]:
clftree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3)

In [23]:
y_train_pred = clftree.predict(X_train)
y_test_pred = clftree.predict(X_test)

In [24]:
y_test_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0])

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [26]:
confusion_matrix(y_train, y_train_pred)

array([[176,  12],
       [140,  76]])

In [27]:
confusion_matrix(y_test, y_test_pred)

array([[36,  6],
       [38, 22]])

In [28]:
accuracy_score(y_test, y_test_pred)

0.5686274509803921

In [29]:
dot_data = tree.export_graphviz(clftree, out_file=None,feature_names= X_train.columns, filled = True)

In [30]:
from IPython.display import Image

In [ ]:
import pydotplus

In [ ]:
graph = pydotplus.graph_from_dot_data(dot_data)
Image(graph.create_png())
